/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Directories.PersonDirectory;
import Business.Entities.Student;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ketanmalik
 */
public class AlertsPanel extends javax.swing.JPanel {

    /**
     * Creates new form AlertsPanel
     */
    private static PersonDirectory pd;
    DefaultTableModel dtmUpper;
    DefaultTableModel dtmLower;

    public AlertsPanel() {
        initComponents();
        pd = PersonDirectory.getObject();
        populateImmunizationTable();
        alertaTitleLabel.setText("Immunization Alerts");
        adminAlertsBtn.setEnabled(true);
        immuneAlertsBtn.setEnabled(false);
        upperTableLabel.setText("Overdue:");
        lowerTableLabel.setText("Upcoming:");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        immuneAlertsBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        overdueAlertsTable = new javax.swing.JTable();
        adminAlertsBtn = new javax.swing.JButton();
        upperTableLabel = new javax.swing.JLabel();
        lowerTableLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        upcomingAlertsTable = new javax.swing.JTable();
        alertaTitleLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 153, 153));

        immuneAlertsBtn.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        immuneAlertsBtn.setText("View Immunization Alerts");
        immuneAlertsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                immuneAlertsBtnActionPerformed(evt);
            }
        });

        overdueAlertsTable.setAutoCreateRowSorter(true);
        overdueAlertsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student Name", "Age (months)", "Vaccine Name", "Past Due (months)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(overdueAlertsTable);
        if (overdueAlertsTable.getColumnModel().getColumnCount() > 0) {
            overdueAlertsTable.getColumnModel().getColumn(0).setResizable(false);
            overdueAlertsTable.getColumnModel().getColumn(1).setResizable(false);
            overdueAlertsTable.getColumnModel().getColumn(2).setResizable(false);
            overdueAlertsTable.getColumnModel().getColumn(3).setResizable(false);
        }

        adminAlertsBtn.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        adminAlertsBtn.setText("View Administrative Alerts");
        adminAlertsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminAlertsBtnActionPerformed(evt);
            }
        });

        upperTableLabel.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        upperTableLabel.setForeground(new java.awt.Color(255, 255, 255));
        upperTableLabel.setText("Overdue:");

        lowerTableLabel.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        lowerTableLabel.setForeground(new java.awt.Color(255, 255, 255));
        lowerTableLabel.setText("Upcoming:");

        upcomingAlertsTable.setAutoCreateRowSorter(true);
        upcomingAlertsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student Name", "Age (months)", "Vaccine Name", "Due In (months)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(upcomingAlertsTable);
        if (upcomingAlertsTable.getColumnModel().getColumnCount() > 0) {
            upcomingAlertsTable.getColumnModel().getColumn(0).setResizable(false);
            upcomingAlertsTable.getColumnModel().getColumn(1).setResizable(false);
            upcomingAlertsTable.getColumnModel().getColumn(2).setResizable(false);
            upcomingAlertsTable.getColumnModel().getColumn(3).setResizable(false);
        }

        alertaTitleLabel.setFont(new java.awt.Font("Arial", 2, 25)); // NOI18N
        alertaTitleLabel.setForeground(new java.awt.Color(255, 255, 255));
        alertaTitleLabel.setText("Administrative Alerts");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(110, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(immuneAlertsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(adminAlertsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(121, 121, 121)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(upperTableLabel)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lowerTableLabel)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(95, 95, 95))
            .addGroup(layout.createSequentialGroup()
                .addGap(343, 343, 343)
                .addComponent(alertaTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(98, Short.MAX_VALUE)
                .addComponent(alertaTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(upperTableLabel)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(immuneAlertsBtn))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(adminAlertsBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(lowerTableLabel)
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(211, 211, 211))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void populateImmunizationTable() {
        dtmUpper = (DefaultTableModel) overdueAlertsTable.getModel();
        dtmLower = (DefaultTableModel) upcomingAlertsTable.getModel();

        dtmUpper.setRowCount(0);
        dtmLower.setRowCount(0);
        for (Student s : pd.getStudentDirectory()) {
            String[] dates = s.getVaccinationRecord().get("Hib").split(",");
            for (String date : dates) {
                if (date.equals("delay")) {
                    Object[] row = new Object[4];
                    row[0] = s;
                    row[1] = s.getAge();
                    row[2] = "Hib";
                    row[3] = -1;
                    dtmUpper.addRow(row);
                } else if (date.equals("na")) {

                } else {
                    if (Integer.parseInt(date) > s.getAge()) {
                        Object[] row = new Object[4];
                        row[0] = s;
                        row[1] = s.getAge();
                        row[2] = "Hib";
                        row[3] = Integer.parseInt(date) - s.getAge();
                        dtmLower.addRow(row);
                    }
                }
            }

            dates = s.getVaccinationRecord().get("DTaP").split(",");
            for (String date : dates) {
                if (date.equals("delay")) {
                    Object[] row = new Object[4];
                    row[0] = s;
                    row[1] = s.getAge();
                    row[2] = "DTaP";
                    row[3] = 12;
                    dtmUpper.addRow(row);
                } else if (date.equals("na")) {

                } else {
                    if (Integer.parseInt(date) > s.getAge()) {
                        Object[] row = new Object[4];
                        row[0] = s;
                        row[1] = s.getAge();
                        row[2] = "DTaP";
                        row[3] = Integer.parseInt(date) - s.getAge();
                        dtmLower.addRow(row);
                    }
                }
            }
            dates = s.getVaccinationRecord().get("Polio").split(",");
            for (String date : dates) {
                if (date.equals("delay")) {
                    Object[] row = new Object[4];
                    row[0] = s;
                    row[1] = s.getAge();
                    row[2] = "Polio";
                    row[3] = 12;
                    dtmUpper.addRow(row);
                } else if (date.equals("na")) {

                } else {
                    if (Integer.parseInt(date) > s.getAge()) {
                        Object[] row = new Object[4];
                        row[0] = s;
                        row[1] = s.getAge();
                        row[2] = "Polio";
                        row[3] = Integer.parseInt(date) - s.getAge();
                        dtmLower.addRow(row);
                    }
                }
            }
            dates = s.getVaccinationRecord().get("HepatitisB").split(",");
            for (String date : dates) {
                if (date.equals("delay")) {
                    Object[] row = new Object[4];
                    row[0] = s;
                    row[1] = s.getAge();
                    row[2] = "Hepatitis B";
                    row[3] = 12;
                    dtmUpper.addRow(row);
                } else if (date.equals("na")) {

                } else {
                    if (Integer.parseInt(date) > s.getAge()) {
                        Object[] row = new Object[4];
                        row[0] = s;
                        row[1] = s.getAge();
                        row[2] = "Hepatitis B";
                        row[3] = Integer.parseInt(date) - s.getAge();
                        dtmLower.addRow(row);
                    }
                }
            }
            dates = s.getVaccinationRecord().get("MMR").split(",");
            for (String date : dates) {
                if (date.equals("delay")) {
                    Object[] row = new Object[4];
                    row[0] = s;
                    row[1] = s.getAge();
                    row[2] = "MMR";
                    row[3] = 12;
                    dtmUpper.addRow(row);
                } else if (date.equals("na")) {

                } else {
                    if (Integer.parseInt(date) > s.getAge()) {
                        Object[] row = new Object[4];
                        row[0] = s;
                        row[1] = s.getAge();
                        row[2] = "MMR";
                        row[3] = Integer.parseInt(date) - s.getAge();
                        dtmLower.addRow(row);
                    }
                }
            }
            dates = s.getVaccinationRecord().get("Varicella").split(",");
            for (String date : dates) {
                if (date.equals("delay")) {
                    Object[] row = new Object[4];
                    row[0] = s;
                    row[1] = s.getAge();
                    row[2] = "Varicella";
                    row[3] = 12;
                    dtmUpper.addRow(row);
                } else if (date.equals("na")) {

                } else {
                    if (Integer.parseInt(date) > s.getAge()) {
                        Object[] row = new Object[4];
                        row[0] = s;
                        row[1] = s.getAge();
                        row[2] = "Varicella";
                        row[3] = Integer.parseInt(date) - s.getAge();
                        dtmLower.addRow(row);
                    }
                }
            }
        }
    }

    private void immuneAlertsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_immuneAlertsBtnActionPerformed
        alertaTitleLabel.setText("Immunization Alerts");
        adminAlertsBtn.setEnabled(true);
        immuneAlertsBtn.setEnabled(false);
        upperTableLabel.setText("Overdue:");
        lowerTableLabel.setText("Upcoming:");
    }//GEN-LAST:event_immuneAlertsBtnActionPerformed

    private void adminAlertsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminAlertsBtnActionPerformed
        alertaTitleLabel.setText("Administrative Alerts");
        adminAlertsBtn.setEnabled(false);
        immuneAlertsBtn.setEnabled(true);
        upperTableLabel.setText("Overdue:");
        lowerTableLabel.setText("Upcoming:");
    }//GEN-LAST:event_adminAlertsBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminAlertsBtn;
    private javax.swing.JLabel alertaTitleLabel;
    private javax.swing.JButton immuneAlertsBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lowerTableLabel;
    private javax.swing.JTable overdueAlertsTable;
    private javax.swing.JTable upcomingAlertsTable;
    private javax.swing.JLabel upperTableLabel;
    // End of variables declaration//GEN-END:variables
}
