/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.MainJFrame;

import Business.Directories.PersonDirectory;
import Business.Entities.Student;
import Business.Util.DbManagement;
import UI.AddUsers.AddStudent;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ketanmalik
 */
public class HomePage extends javax.swing.JPanel {

    /**
     * Creates new form HomePage
     */
    private JPanel displayPanel;
    private PersonDirectory personDirectory;

    public HomePage(JPanel displayPanel) {
        initComponents();
        this.displayPanel = displayPanel;
        this.personDirectory = PersonDirectory.getObject();
        populateStudentTable();
        modifyButtons();
        showButtons(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tchrTbl = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        stuTbl = new javax.swing.JTable();
        stuAdd = new javax.swing.JButton();
        stuView = new javax.swing.JButton();
        stuUpdate = new javax.swing.JButton();
        stuDelete = new javax.swing.JButton();
        tchrAdd = new javax.swing.JButton();
        tchrView = new javax.swing.JButton();
        tchrUpdate = new javax.swing.JButton();
        tchrDelete = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));

        tchrTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Age"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tchrTbl);
        if (tchrTbl.getColumnModel().getColumnCount() > 0) {
            tchrTbl.getColumnModel().getColumn(0).setResizable(false);
            tchrTbl.getColumnModel().getColumn(1).setResizable(false);
            tchrTbl.getColumnModel().getColumn(2).setResizable(false);
        }

        stuTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Age (months)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(stuTbl);
        if (stuTbl.getColumnModel().getColumnCount() > 0) {
            stuTbl.getColumnModel().getColumn(0).setResizable(false);
            stuTbl.getColumnModel().getColumn(1).setResizable(false);
            stuTbl.getColumnModel().getColumn(2).setResizable(false);
        }

        stuAdd.setText("Add");
        stuAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stuAddActionPerformed(evt);
            }
        });

        stuView.setText("View");
        stuView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stuViewActionPerformed(evt);
            }
        });

        stuUpdate.setText("Update");
        stuUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stuUpdateActionPerformed(evt);
            }
        });

        stuDelete.setText("Delete");
        stuDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stuDeleteActionPerformed(evt);
            }
        });

        tchrAdd.setText("Add");

        tchrView.setText("View");

        tchrUpdate.setText("Update");

        tchrDelete.setText("Delete");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 770, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(stuAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(stuView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(stuUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(stuDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(tchrAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tchrView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tchrUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tchrDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(240, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(stuAdd)
                        .addGap(18, 18, 18)
                        .addComponent(stuView)
                        .addGap(18, 18, 18)
                        .addComponent(stuUpdate)
                        .addGap(18, 18, 18)
                        .addComponent(stuDelete)
                        .addGap(97, 97, 97)
                        .addComponent(tchrAdd)
                        .addGap(18, 18, 18)
                        .addComponent(tchrView)
                        .addGap(18, 18, 18)
                        .addComponent(tchrUpdate)
                        .addGap(18, 18, 18)
                        .addComponent(tchrDelete)))
                .addContainerGap(224, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void stuAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stuAddActionPerformed
        AddStudent addStudent = new AddStudent(displayPanel, "add", null);
        displayPanel.add("addStudent", addStudent);
        CardLayout layout = (CardLayout) displayPanel.getLayout();
        layout.next(displayPanel);
    }//GEN-LAST:event_stuAddActionPerformed

    private void stuViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stuViewActionPerformed
        int selectedRow = stuTbl.getSelectedRow();
        if (selectedRow >= 0) {
            Student student = (Student) stuTbl.getValueAt(selectedRow, 1);
            AddStudent viewStudent = new AddStudent(displayPanel, "view", student);
            displayPanel.add("viewStudent", viewStudent);
            CardLayout layout = (CardLayout) displayPanel.getLayout();
            layout.next(displayPanel);
        } else {
            JOptionPane.showMessageDialog(null, "Please select a row to view", "No selection zfound", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_stuViewActionPerformed

    private void stuUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stuUpdateActionPerformed
        int selectedRow = stuTbl.getSelectedRow();
        if (selectedRow >= 0) {
            Student student = (Student) stuTbl.getValueAt(selectedRow, 1);
            AddStudent updateStudent = new AddStudent(displayPanel, "update", student);
            displayPanel.add("updateStudent", updateStudent);
            CardLayout layout = (CardLayout) displayPanel.getLayout();
            layout.next(displayPanel);
        } else {
            JOptionPane.showMessageDialog(null, "Please select a row to update", "No selection found", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_stuUpdateActionPerformed

    private void stuDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stuDeleteActionPerformed
        int selectedRow = stuTbl.getSelectedRow();
        if (selectedRow >= 0) {
            int id = (Integer) stuTbl.getValueAt(selectedRow, 0);
            DbManagement.deleteFromStudentDB(String.valueOf(id));
            if (personDirectory.getStudentDirectory().contains(stuTbl.getValueAt(selectedRow, 1))) {
                personDirectory.getStudentDirectory().remove(stuTbl.getValueAt(selectedRow, 1));
            }
            populateStudentTable();
        } else {
            JOptionPane.showMessageDialog(null, "Please select a row to delete", "No selection found", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_stuDeleteActionPerformed

    public void populateStudentTable() {
        DefaultTableModel dtm = (DefaultTableModel) stuTbl.getModel();

        dtm.setRowCount(0);
        for (Student s : personDirectory.getStudentDirectory()) {
            Object[] row = new Object[3];
            row[0] = s.getId();
            row[1] = s;
            row[2] = s.getAge();

            dtm.addRow(row);
        }
    }

    private void modifyButtons() {
//        MainJFrame.manageNetworkBtn.setText("Manage Network");
//        MainJFrame.manageNetworkBtn.setOpaque(false);
//        MainJFrame.manageNetworkBtn.setContentAreaFilled(false);
//        MainJFrame.manageNetworkBtn.setBorderPainted(false);
//        MainJFrame.manageNetworkBtn.setForeground(Color.black);
//
//        MainJFrame.manageEnterpriseBtn.setText("Manage Enterprise");
//        MainJFrame.manageEnterpriseBtn.setOpaque(false);
//        MainJFrame.manageEnterpriseBtn.setContentAreaFilled(false);
//        MainJFrame.manageEnterpriseBtn.setBorderPainted(false);
//        MainJFrame.manageEnterpriseBtn.setForeground(Color.white);
//
//        MainJFrame.manageAdminBtn.setText("Manage Enterprise Admin");
//        MainJFrame.manageAdminBtn.setOpaque(false);
//        MainJFrame.manageAdminBtn.setContentAreaFilled(false);
//        MainJFrame.manageAdminBtn.setBorderPainted(false);
//        MainJFrame.manageAdminBtn.setForeground(Color.white);

        MainJFrame.signOutBtn.setOpaque(false);
        MainJFrame.signOutBtn.setContentAreaFilled(false);
        MainJFrame.signOutBtn.setBorderPainted(false);
    }

    public void showButtons(boolean bool) {
        MainJFrame.signOutBtn.setVisible(bool);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton stuAdd;
    private javax.swing.JButton stuDelete;
    private javax.swing.JTable stuTbl;
    private javax.swing.JButton stuUpdate;
    private javax.swing.JButton stuView;
    private javax.swing.JButton tchrAdd;
    private javax.swing.JButton tchrDelete;
    private javax.swing.JTable tchrTbl;
    private javax.swing.JButton tchrUpdate;
    private javax.swing.JButton tchrView;
    // End of variables declaration//GEN-END:variables
}
