/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.ManageUsers;

import Business.Configuration.ConfigureDayCare;
import Business.Directories.ClassroomDirectory;
import Business.Directories.PersonDirectory;
import Business.Directories.TeacherStudentDirectory;
import Business.Entities.AbstractPerson;
import Business.Entities.Student;
import Business.Factory.StudentFactory;
import Business.Util.DateUtil;
import Business.Util.DbManagement;
import UI.MainJFrame.HomePage;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author ketanmalik
 */
public class ManageStudents extends javax.swing.JPanel {

    /**
     * Creates new form ManageStudents
     */
    private JPanel displayPanel;
    private String mode = "";
    private PersonDirectory personDirectory;
    private Student student;
    private ClassroomDirectory cd;

    public ManageStudents(JPanel displayPanel, String mode, Student student) {
        initComponents();
        cd = ClassroomDirectory.getObject();
        this.displayPanel = displayPanel;
        this.personDirectory = PersonDirectory.getObject();
        this.mode = mode;
        this.student = student;
        if (mode.equals("add")) {
            pageTitle.setText("Add Student");
            enableFields(true);
            idTxtField.setText(String.valueOf(personDirectory.getStudentDirectory().size() + 1));
            registerDate.setText(DateUtil.getDateToString(new Date()));
        } else if (mode.equals("view")) {
            pageTitle.setText("View Student");
            enableFields(false);
            idTxtField.setText(String.valueOf(student.getId()));
            registerDate.setText(DateUtil.getDateToString(student.getDate()));
            updateFields();
        } else if (mode.equals("update")) {
            pageTitle.setText("Update Student");
            enableFields(true);
            idTxtField.setText(String.valueOf(student.getId()));
            registerDate.setText(DateUtil.getDateToString(student.getDate()));
            updateFields();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        phoneTxtField = new javax.swing.JTextField();
        ageTxtField = new javax.swing.JTextField();
        fNameTxtField = new javax.swing.JTextField();
        mNameTxtField = new javax.swing.JTextField();
        addressTxtField = new javax.swing.JTextField();
        nameTxtField = new javax.swing.JTextField();
        birthDateTxtField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        label = new javax.swing.JLabel();
        hib1 = new javax.swing.JComboBox<>();
        hib2 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        hib3 = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        hib4 = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        dtap4 = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        polio3 = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        hepatitisb1 = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        mmr1 = new javax.swing.JComboBox<>();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        dtap5 = new javax.swing.JComboBox<>();
        jLabel39 = new javax.swing.JLabel();
        dtap1 = new javax.swing.JComboBox<>();
        dtap2 = new javax.swing.JComboBox<>();
        dtap3 = new javax.swing.JComboBox<>();
        polio1 = new javax.swing.JComboBox<>();
        jLabel26 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        polio2 = new javax.swing.JComboBox<>();
        polio4 = new javax.swing.JComboBox<>();
        label1 = new javax.swing.JLabel();
        hepatitisb2 = new javax.swing.JComboBox<>();
        hepatitisb3 = new javax.swing.JComboBox<>();
        mmr2 = new javax.swing.JComboBox<>();
        jLabel35 = new javax.swing.JLabel();
        varicella2 = new javax.swing.JComboBox<>();
        varicella1 = new javax.swing.JComboBox<>();
        jLabel36 = new javax.swing.JLabel();
        confirmBtn = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        idTxtField = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        backBtn2 = new javax.swing.JButton();
        pageTitle = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        registerDate = new javax.swing.JTextField();

        setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Birth Day:");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name:");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Age:");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Father's Name:");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Mother's Name:");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Address:");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Phone Number:");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("At what age (months)  will the child receive/has received the following vaccinations: ");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Hib Dose:");

        label.setForeground(new java.awt.Color(255, 255, 255));
        label.setText("1st");

        hib1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4" }));

        hib2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "4", "5", "6" }));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("2nd");

        hib3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "6", "7", "8" }));

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("3rd");

        hib4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "12", "13", "14", "15" }));

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("4th");

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("2nd");

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("3rd");

        dtap4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "15", "16", "17", "18" }));

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("4th");

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Dtap Dose:");

        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("1st");

        polio3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18" }));

        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("3rd");

        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("4th");

        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Polio Dose:");

        hepatitisb1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0" }));

        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("2nd");

        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("3rd");

        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("HepatitisB:");

        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("1st");

        mmr1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "12", "13", "14", "15" }));

        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("MMR:");

        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("1st");

        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("Varicella:");

        dtap5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", "66", "67", "68", "69", "70", "71", "72" }));

        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("5th");

        dtap1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4" }));

        dtap2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "4", "5", "6" }));

        dtap3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "6", "7", "8" }));

        polio1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4" }));

        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("1st");

        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("2nd");

        polio2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "4", "5", "6" }));

        polio4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", "66", "67", "68", "69", "70", "71", "72" }));

        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setText("2nd");

        hepatitisb2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2" }));

        hepatitisb3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18" }));

        mmr2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", "66", "67", "68", "69", "70", "71", "72" }));

        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("2nd");

        varicella2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", "66", "67", "68", "69", "70", "71", "72" }));

        varicella1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "12", "13", "14", "15" }));

        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("1st");

        confirmBtn.setText("Confirm");
        confirmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmBtnActionPerformed(evt);
            }
        });

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("ID:");

        idTxtField.setEnabled(false);

        jLabel19.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("General Details:");

        jLabel23.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Vaccination Details:");

        backBtn2.setText("Back");
        backBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtn2ActionPerformed(evt);
            }
        });

        pageTitle.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        pageTitle.setForeground(new java.awt.Color(255, 255, 255));
        pageTitle.setText("Add Student");

        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Registration Date:");

        registerDate.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backBtn2)
                        .addGap(225, 225, 225)
                        .addComponent(pageTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(idTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel29)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(registerDate, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(nameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(4, 4, 4)
                                        .addComponent(ageTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(birthDateTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(101, 101, 101)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addressTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phoneTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel23)
                    .addComponent(jLabel8)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel32)
                            .addComponent(jLabel27)
                            .addComponent(jLabel22)
                            .addComponent(jLabel17)
                            .addComponent(jLabel9)
                            .addComponent(jLabel37))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel36)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(varicella1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel33)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(mmr1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel35)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(varicella2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel24)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(mmr2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(label)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(hib1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(hib2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(hib3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(hib4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel26)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(polio1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel18)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(dtap1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel14)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(dtap2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel15)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(dtap3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel16)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(dtap4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(confirmBtn)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel30)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(polio2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(jLabel20)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(polio3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(jLabel21)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(polio4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel39)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dtap5, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel28)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hepatitisb1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(label1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hepatitisb2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hepatitisb3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backBtn2)
                    .addComponent(pageTitle))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(fNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(mNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(addressTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(phoneTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(83, 83, 83))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(idTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29)
                            .addComponent(registerDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(nameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(birthDateTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(ageTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56)))
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(label)
                    .addComponent(hib1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(hib2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(hib3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(hib4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(dtap1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(dtap2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(dtap3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(dtap4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel39)
                    .addComponent(dtap5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel26)
                    .addComponent(polio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30)
                    .addComponent(polio2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(polio3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(polio4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(jLabel28)
                    .addComponent(hepatitisb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label1)
                    .addComponent(hepatitisb2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25)
                    .addComponent(hepatitisb3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(jLabel33)
                    .addComponent(mmr1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(mmr2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(jLabel36)
                    .addComponent(varicella1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35)
                    .addComponent(varicella2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(confirmBtn)
                .addContainerGap(38, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void enableFields(boolean bool) {
        confirmBtn.setEnabled(bool);
        nameTxtField.setEnabled(bool);
        birthDateTxtField.setEnabled(bool);
        fNameTxtField.setEnabled(bool);
        mNameTxtField.setEnabled(bool);
        addressTxtField.setEnabled(bool);
        phoneTxtField.setEnabled(bool);
        ageTxtField.setEnabled(bool);
        hib1.setEnabled(bool);
        hib2.setEnabled(bool);
        hib3.setEnabled(bool);
        hib4.setEnabled(bool);
        dtap1.setEnabled(bool);
        dtap2.setEnabled(bool);
        dtap3.setEnabled(bool);
        dtap4.setEnabled(bool);
        dtap5.setEnabled(bool);
        polio1.setEnabled(bool);
        polio2.setEnabled(bool);
        polio3.setEnabled(bool);
        polio4.setEnabled(bool);
        hepatitisb1.setEnabled(bool);
        hepatitisb2.setEnabled(bool);
        hepatitisb3.setEnabled(bool);
        mmr1.setEnabled(bool);
        mmr2.setEnabled(bool);
        varicella1.setEnabled(bool);
        varicella2.setEnabled(bool);

    }

    private void updateFields() {
        idTxtField.setText(String.valueOf(student.getId()));
        registerDate.setText(DateUtil.getDateToString(student.getDate()));
        nameTxtField.setText(String.valueOf(student.getName()));
        birthDateTxtField.setText(DateUtil.getDateToString(student.getBirthDate()));
        ageTxtField.setText(String.valueOf(student.getAge()));
        fNameTxtField.setText(student.getFathersName());
        mNameTxtField.setText(student.getMothersName());
        addressTxtField.setText(student.getAddress());
        phoneTxtField.setText(student.getPhone());
        List<Integer> hibList = student.getVaccinationHistory().get("Hib");
        hib1.setSelectedItem(String.valueOf(hibList.get(0)));
        hib2.setSelectedItem(String.valueOf(hibList.get(1)));
        hib3.setSelectedItem(String.valueOf(hibList.get(2)));
        hib4.setSelectedItem(String.valueOf(hibList.get(3)));

        List<Integer> dtapList = student.getVaccinationHistory().get("Dtap");
        dtap1.setSelectedItem(String.valueOf(dtapList.get(0)));
        dtap2.setSelectedItem(String.valueOf(dtapList.get(1)));
        dtap3.setSelectedItem(String.valueOf(dtapList.get(2)));
        dtap4.setSelectedItem(String.valueOf(dtapList.get(3)));
        dtap5.setSelectedItem(String.valueOf(dtapList.get(4)));

        List<Integer> polioList = student.getVaccinationHistory().get("Polio");
        polio1.setSelectedItem(String.valueOf(polioList.get(0)));
        polio2.setSelectedItem(String.valueOf(polioList.get(1)));
        polio3.setSelectedItem(String.valueOf(polioList.get(2)));
        polio4.setSelectedItem(String.valueOf(polioList.get(3)));

        List<Integer> hepatitisbList = student.getVaccinationHistory().get("HepatitisB");
        hepatitisb1.setSelectedItem(String.valueOf(hepatitisbList.get(0)));
        hepatitisb2.setSelectedItem(String.valueOf(hepatitisbList.get(1)));
        hepatitisb3.setSelectedItem(String.valueOf(hepatitisbList.get(2)));

        List<Integer> mmrList = student.getVaccinationHistory().get("MMR");
        mmr1.setSelectedItem(String.valueOf(mmrList.get(0)));
        mmr2.setSelectedItem(String.valueOf(mmrList.get(1)));

        List<Integer> varicellaList = student.getVaccinationHistory().get("Varicella");
        varicella1.setSelectedItem(String.valueOf(varicellaList.get(0)));
        varicella2.setSelectedItem(String.valueOf(varicellaList.get(1)));

    }

    private void backBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtn2ActionPerformed
        displayPanel.remove(this);
        Component[] componentArray = displayPanel.getComponents();
        Component component = componentArray[componentArray.length - 1];
        HomePage hp = (HomePage) component;
        hp.populateStudentTable();
        CardLayout layout = (CardLayout) displayPanel.getLayout();
        layout.previous(displayPanel);
    }//GEN-LAST:event_backBtn2ActionPerformed

    private void confirmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmBtnActionPerformed
        String name = nameTxtField.getText();
        if (name == null || name.equals("")) {
            JOptionPane.showMessageDialog(null, "Please enter valid name", "Invalid Entry", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String bday = birthDateTxtField.getText();
        if (bday == null || bday.equals("")) {
            JOptionPane.showMessageDialog(null, "Please enter valid birthday", "Invalid Entry", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            Integer.parseInt(ageTxtField.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Please enter valid age", "Invalid Entry", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int age = Integer.parseInt(ageTxtField.getText());
        String fName = fNameTxtField.getText();
        if (fName == null || fName.equals("")) {
            JOptionPane.showMessageDialog(null, "Please enter valid Father's Name", "Invalid Entry", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String mName = mNameTxtField.getText();
        if (mName == null || mName.equals("")) {
            JOptionPane.showMessageDialog(null, "Please enter Mother's Name", "Invalid Entry", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String address = addressTxtField.getText();
        if (address == null || address.equals("")) {
            JOptionPane.showMessageDialog(null, "Please enter valid address", "Invalid Entry", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String phoneNo = phoneTxtField.getText();
        if (phoneNo == null || phoneNo.equals("")) {
            JOptionPane.showMessageDialog(null, "Please enter valid phone number", "Invalid Entry", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String id = idTxtField.getText();
        String registerDate = DateUtil.getDateToString(new Date());
        String grade = "0";
        String hib1 = String.valueOf(this.hib1.getSelectedItem());
        String hib2 = String.valueOf(this.hib2.getSelectedItem());
        String hib3 = String.valueOf(this.hib3.getSelectedItem());
        String hib4 = String.valueOf(this.hib4.getSelectedItem());
        String hib = hib1.concat(",").concat(hib2).concat(",").concat(hib3).concat(",").concat(hib4);

        String dtap1 = String.valueOf(this.dtap1.getSelectedItem());
        String dtap2 = String.valueOf(this.dtap2.getSelectedItem());
        String dtap3 = String.valueOf(this.dtap3.getSelectedItem());
        String dtap4 = String.valueOf(this.dtap4.getSelectedItem());
        String dtap5 = String.valueOf(this.dtap5.getSelectedItem());
        String dtap = dtap1.concat(",").concat(dtap2).concat(",").concat(dtap3).concat(",").concat(dtap4).concat(",").concat(dtap5);

        String polio1 = String.valueOf(this.polio1.getSelectedItem());
        String polio2 = String.valueOf(this.polio2.getSelectedItem());
        String polio3 = String.valueOf(this.polio3.getSelectedItem());
        String polio4 = String.valueOf(this.polio4.getSelectedItem());
        String polio = polio1.concat(",").concat(polio2).concat(",").concat(polio3).concat(",").concat(polio4);

        String hepatitisb1 = String.valueOf(this.hepatitisb1.getSelectedItem());
        String hepatitisb2 = String.valueOf(this.hepatitisb2.getSelectedItem());
        String hepatitisb3 = String.valueOf(this.hepatitisb3.getSelectedItem());
        String hepatitisb = hepatitisb1.concat(",").concat(hepatitisb2).concat(",").concat(hepatitisb3);

        String mmr1 = String.valueOf(this.mmr1.getSelectedItem());
        String mmr2 = String.valueOf(this.mmr2.getSelectedItem());
        String mmr = mmr1.concat(",").concat(mmr2);

        String varicella1 = String.valueOf(this.varicella1.getSelectedItem());
        String varicella2 = String.valueOf(this.varicella2.getSelectedItem());
        String varicella = varicella1.concat(",").concat(varicella2);

        if (mode.equals("add")) {

            if (age >= 6 && age <= 12) {
                long availableTeachers = personDirectory.getTeacherDirectory().stream().filter(e -> e.getCategory().equals("6-12")).count();
                if (personDirectory.getStudentDirectory().stream().filter(e -> e.getAge() >= 6 && e.getAge() <= 12).count() >= (4 * availableTeachers)) {
                    JOptionPane.showMessageDialog(null, "Cannot add more students of age 6-12");
                    return;
                }
            } else if (age >= 13 && age <= 24) {
                long availableTeachers = personDirectory.getTeacherDirectory().stream().filter(e -> e.getCategory().equals("13-24")).count();
                if (personDirectory.getStudentDirectory().stream().filter(e -> e.getAge() >= 13 && e.getAge() <= 24).count() >= (5 * availableTeachers)) {
                    JOptionPane.showMessageDialog(null, "Cannot add more students of age 13-24");
                    return;
                }
            } else if (age >= 25 && age <= 35) {
                long availableTeachers = personDirectory.getTeacherDirectory().stream().filter(e -> e.getCategory().equals("25-35")).count();
                if (personDirectory.getStudentDirectory().stream().filter(e -> e.getAge() >= 25 && e.getAge() <= 35).count() >= (6 * availableTeachers)) {
                    JOptionPane.showMessageDialog(null, "Cannot add more students of age 25-35");
                    return;
                }
            } else if (age >= 36 && age <= 47) {
                long availableTeachers = personDirectory.getTeacherDirectory().stream().filter(e -> e.getCategory().equals("36-47")).count();
                if (personDirectory.getStudentDirectory().stream().filter(e -> e.getAge() >= 36 && e.getAge() <= 47).count() >= (8 * availableTeachers)) {
                    JOptionPane.showMessageDialog(null, "Cannot add more students of age 36-47");
                    return;
                }
            } else if (age >= 48 && age <= 59) {
                long availableTeachers = personDirectory.getTeacherDirectory().stream().filter(e -> e.getCategory().equals("48-59")).count();
                if (personDirectory.getStudentDirectory().stream().filter(e -> e.getAge() >= 48 && e.getAge() <= 59).count() >= (12 * availableTeachers)) {
                    JOptionPane.showMessageDialog(null, "Cannot add more students of age 48-59");
                    return;
                }
            } else if (age >= 60) {
                long availableTeachers = personDirectory.getTeacherDirectory().stream().filter(e -> e.getCategory().equals("60 above")).count();
                if (personDirectory.getStudentDirectory().stream().filter(e -> e.getAge() >= 60).count() >= (15 * availableTeachers)) {
                    JOptionPane.showMessageDialog(null, "Cannot add more students of age more than 59");
                    return;
                }
            }
            DbManagement.saveToStudentDB(id, name, ageTxtField.getText(), fName, mName, address, phoneNo, grade, hib, dtap, polio, hepatitisb, mmr, varicella, registerDate, bday);
            AbstractPerson student = new StudentFactory().getObjectFromUI(Integer.parseInt(idTxtField.getText()), name, age, fName, mName, address, phoneNo, Double.parseDouble(grade), registerDate, bday, hib, dtap, polio, hepatitisb, mmr, varicella);
            personDirectory.getStudentDirectory().add((Student) student);
            TeacherStudentDirectory tsd = TeacherStudentDirectory.getObject();
            tsd.getTeacherStudentGroup().clear();
            ClassroomDirectory cd = ClassroomDirectory.getObject();
            cd.getClassroomDirectory().clear();
            ConfigureDayCare.initializeClassroomGroup();
            ConfigureDayCare.initializeStudentTeacherGroup();
        } else if (mode.equals("update")) {
            DbManagement.updateToStudentDB(name, ageTxtField.getText(), fName, mName, address, phoneNo, hib, dtap, polio, hepatitisb, mmr, varicella, bday, idTxtField.getText());
            updateStudentInDirectory(name, age, fName, mName, address, phoneNo, bday, hib, dtap, polio, hepatitisb, mmr, varicella);
            TeacherStudentDirectory tsd = TeacherStudentDirectory.getObject();
            tsd.getTeacherStudentGroup().clear();
            ClassroomDirectory cd = ClassroomDirectory.getObject();
            cd.getClassroomDirectory().clear();
            ConfigureDayCare.initializeClassroomGroup();
            ConfigureDayCare.initializeStudentTeacherGroup();
        }
    }//GEN-LAST:event_confirmBtnActionPerformed

    private void updateStudentInDirectory(String name, int age, String fName, String mName, String address, String phoneNo, String bday, String hib, String dtap, String polio, String hepatitisb, String mmr, String varicella) {
        student.setName(name);
        student.setAge(age);
        student.setFathersName(fName);
        student.setMothersName(mName);
        student.setAddress(address);
        student.setPhone(phoneNo);
        student.setBirthDate(DateUtil.getStringToDate(bday));
        String fields[] = hib.split(",");
        List<Integer> list = new ArrayList<>();
        for (int i = 0; i < fields.length; i++) {
            list.add(Integer.parseInt(fields[i]));
        }
        student.getVaccinationHistory().put("Hib", list);
        fields = null;
        list = new ArrayList<>();

        fields = dtap.split(",");
        for (int i = 0; i < fields.length; i++) {
            list.add(Integer.parseInt(fields[i]));
        }
        student.getVaccinationHistory().put("Dtap", list);
        fields = null;
        list = new ArrayList<>();

        fields = polio.split(",");
        for (int i = 0; i < fields.length; i++) {
            list.add(Integer.parseInt(fields[i]));
        }
        student.getVaccinationHistory().put("Polio", list);
        fields = null;
        list = new ArrayList<>();

        fields = hepatitisb.split(",");
        for (int i = 0; i < fields.length; i++) {
            list.add(Integer.parseInt(fields[i]));
        }
        student.getVaccinationHistory().put("HepatitisB", list);
        fields = null;
        list = new ArrayList<>();

        fields = mmr.split(",");
        for (int i = 0; i < fields.length; i++) {
            list.add(Integer.parseInt(fields[i]));
        }
        student.getVaccinationHistory().put("MMR", list);
        fields = null;
        list = new ArrayList<>();

        fields = varicella.split(",");
        for (int i = 0; i < fields.length; i++) {
            list.add(Integer.parseInt(fields[i]));
        }
        student.getVaccinationHistory().put("Varicella", list);
        fields = null;
        list = new ArrayList<>();

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressTxtField;
    private javax.swing.JTextField ageTxtField;
    private javax.swing.JButton backBtn2;
    private javax.swing.JTextField birthDateTxtField;
    private javax.swing.JButton confirmBtn;
    private javax.swing.JComboBox<String> dtap1;
    private javax.swing.JComboBox<String> dtap2;
    private javax.swing.JComboBox<String> dtap3;
    private javax.swing.JComboBox<String> dtap4;
    private javax.swing.JComboBox<String> dtap5;
    private javax.swing.JTextField fNameTxtField;
    private javax.swing.JComboBox<String> hepatitisb1;
    private javax.swing.JComboBox<String> hepatitisb2;
    private javax.swing.JComboBox<String> hepatitisb3;
    private javax.swing.JComboBox<String> hib1;
    private javax.swing.JComboBox<String> hib2;
    private javax.swing.JComboBox<String> hib3;
    private javax.swing.JComboBox<String> hib4;
    private javax.swing.JTextField idTxtField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel label;
    private javax.swing.JLabel label1;
    private javax.swing.JTextField mNameTxtField;
    private javax.swing.JComboBox<String> mmr1;
    private javax.swing.JComboBox<String> mmr2;
    private javax.swing.JTextField nameTxtField;
    private javax.swing.JLabel pageTitle;
    private javax.swing.JTextField phoneTxtField;
    private javax.swing.JComboBox<String> polio1;
    private javax.swing.JComboBox<String> polio2;
    private javax.swing.JComboBox<String> polio3;
    private javax.swing.JComboBox<String> polio4;
    private javax.swing.JTextField registerDate;
    private javax.swing.JComboBox<String> varicella1;
    private javax.swing.JComboBox<String> varicella2;
    // End of variables declaration//GEN-END:variables
}
