/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.Alerts;

import Business.Directories.PersonDirectory;
import Business.Entities.Student;
import Business.Util.DateUtil;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.Set;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ketanmalik
 */
public class ManageImmunizationPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageImmunizationPanel
     */
    private JPanel displayPanel;
    private PersonDirectory personDirectory;

    public ManageImmunizationPanel(JPanel displayPanel) {
        this.displayPanel = displayPanel;
        personDirectory = PersonDirectory.getObject();
        initComponents();
        populateStudentDropdown();
        populateFields(personDirectory.getStudentDirectory().get(0));
        populateTable(personDirectory.getStudentDirectory().get(0), 7);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backBtn2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        studentDropdown = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        filterDropdown = new javax.swing.JComboBox<>();
        pastDueBtn = new javax.swing.JButton();
        idTxtField = new javax.swing.JTextField();
        nameTxtField = new javax.swing.JTextField();
        bdayTxtField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        filterTbl = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));

        backBtn2.setText("Back");
        backBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtn2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Manage Immunization Alerts");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID:");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Name:");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Birthday:");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Student:");

        studentDropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        studentDropdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentDropdownActionPerformed(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Due In:");

        filterDropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Next 7 Days", "Next 15 Days", "Next 30 Days" }));
        filterDropdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterDropdownActionPerformed(evt);
            }
        });

        pastDueBtn.setText("Past Due");

        idTxtField.setEnabled(false);

        nameTxtField.setEnabled(false);

        bdayTxtField.setEnabled(false);

        filterTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Vaccination", "Dose", "Due Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(filterTbl);
        if (filterTbl.getColumnModel().getColumnCount() > 0) {
            filterTbl.getColumnModel().getColumn(0).setResizable(false);
            filterTbl.getColumnModel().getColumn(1).setResizable(false);
            filterTbl.getColumnModel().getColumn(2).setResizable(false);
        }

        jButton1.setText("Send Reminder");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(backBtn2)
                                .addGap(398, 398, 398)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(studentDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(filterDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(143, 143, 143)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel5))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(idTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(nameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(bdayTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pastDueBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(406, 406, 406)
                        .addComponent(jButton1)))
                .addContainerGap(280, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(backBtn2))
                .addGap(105, 105, 105)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(studentDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(filterDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pastDueBtn))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(idTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(nameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(bdayTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addComponent(jButton1)
                .addContainerGap(147, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void populateStudentDropdown() {
        studentDropdown.removeAllItems();
        for (Student s : personDirectory.getStudentDirectory()) {
            studentDropdown.addItem(s.getName());
        }
    }

    public void populateFields(Student s) {
        idTxtField.setText(String.valueOf(s.getId()));
        nameTxtField.setText(s.getName());
        bdayTxtField.setText(DateUtil.getDateToString(s.getBirthDate()));
    }

    public void populateTable(Student s, int filter) {
        DefaultTableModel dtm = (DefaultTableModel) filterTbl.getModel();
        dtm.setRowCount(0);

        Map<String, List<Integer>> vaccinationHistory = new HashMap<>();
        vaccinationHistory = s.getVaccinationHistory();
        Set<Map.Entry<String, List<Integer>>> entrySet = vaccinationHistory.entrySet();
        Iterator<Map.Entry<String, List<Integer>>> itr = entrySet.iterator();
        while (itr.hasNext()) {
            Map.Entry<String, List<Integer>> e = (Map.Entry<String, List<Integer>>) itr.next();
            for (Integer i : e.getValue()) {
                if (i >= s.getAge()) {
                    if ((i - s.getAge() == 1)) {
                        int dueIn = DateUtil.getDueDate(s.getBirthDate(), i);
                        if (dueIn <= filter) {
                            Object[] row = new Object[3];
                            row[0] = e.getKey();
                            row[1] = e.getValue().indexOf(i) + 1;
                            row[2] = DateUtil.getDateToString(DateUtil.plusDays(s.getBirthDate(), dueIn));

                            dtm.addRow(row);
                        }
                    }
                }
            }
        }
    }

    private void backBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtn2ActionPerformed
        displayPanel.remove(this);
        Component[] componentArray = displayPanel.getComponents();
        Component component = componentArray[componentArray.length - 1];
        AlertsJPanel ap = (AlertsJPanel) component;
        ap.populateAdministrativeTable();
        ap.populateImmunizationTable();
        CardLayout layout = (CardLayout) displayPanel.getLayout();
        layout.previous(displayPanel);
    }//GEN-LAST:event_backBtn2ActionPerformed

    private void filterDropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterDropdownActionPerformed
        applyFilter();
    }//GEN-LAST:event_filterDropdownActionPerformed

    private void studentDropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentDropdownActionPerformed
        applyFilter();
    }//GEN-LAST:event_studentDropdownActionPerformed

    private void applyFilter() {
        String name = (String) studentDropdown.getSelectedItem();
        if (name != null) {
            int filter = 0;
            Student s = null;
            for (Student stu : personDirectory.getStudentDirectory()) {
                if (stu.getName().equals(name)) {
                    s = stu;
                    break;
                }
            }
            String f = (String) filterDropdown.getSelectedItem();
            if (f.equalsIgnoreCase("next 7 days")) {
                filter = 7;
            } else if (f.equalsIgnoreCase("next 15 days")) {
                filter = 15;
            } else if (f.equalsIgnoreCase("next 30 days")) {
                filter = 30;
            }
            populateTable(s, filter);
            populateFields(s);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn2;
    private javax.swing.JTextField bdayTxtField;
    private javax.swing.JComboBox<String> filterDropdown;
    private javax.swing.JTable filterTbl;
    private javax.swing.JTextField idTxtField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameTxtField;
    private javax.swing.JButton pastDueBtn;
    private javax.swing.JComboBox<String> studentDropdown;
    // End of variables declaration//GEN-END:variables
}
